# Generated by Django 4.2a1 on 2023-02-12 00:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0002_tarea_fechadesde_tarea_fechahasta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='fechaDesde',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='fechaHasta',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
