# Generated by Django 4.1.6 on 2023-02-12 04:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0003_alter_tarea_fechadesde_alter_tarea_fechahasta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='fechaDesde',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='fechaHasta',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
