# Generated by Django 4.1.6 on 2023-02-12 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0004_alter_tarea_fechadesde_alter_tarea_fechahasta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='fechaDesde',
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='fechaHasta',
        ),
    ]
