# Generated by Django 4.1.6 on 2023-02-12 05:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0005_remove_tarea_fechadesde_remove_tarea_fechahasta'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='fechaDesde',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='tarea',
            name='fechaHasta',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
